export const PAGE_SIZE_CONFIG = {
  LARGE_PAGE_SIZE: 100000,
  DEFAULT_PAGE_SIZE: 20,
  SMALL_PAGE_SIZE: 10,
} as const

export const { LARGE_PAGE_SIZE, DEFAULT_PAGE_SIZE, SMALL_PAGE_SIZE } = PAGE_SIZE_CONFIG
